### PR TITLE
Debugging coverage

### PR DESCRIPTION
**Pull request by stevepeak**
Trying to see where the coverage report ended up

### CODE REVIEW

**Comment by stevepeak** [comment]
Sorry, didn't mean for this to be merged. I was more looking to see what data is produced.

**Comment by friscoMad** [comment]
Don't worry, it was my fault.
Tell me if you need something done to help identifying the issue.
lcov.info it is where it should be on my pc (W7)

2016-06-07 16:12 GMT+02:00 Steve Peak notifications@github.com:

**Comment by stevepeak** [comment]
Can you check the contents of the file? The uploads to codecov are simply empty.

``` bash
ls -al coverage
# check file contents
cat coverage/lcov.info
# run codecov in debug mode
bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -d
```

**Comment by friscoMad** [comment]
Ok I found it looking at the istanbul exit message.
mocha bin is a wrapper and istanbul does not work with subproccess, that is
documented for windows but I thought it was ok on linux.
The solution is calling directly the child _mocha and everything works as
expected (using codecov package, bash script does not work:
https://travis-ci.org/frisco82/botCommander/jobs/135889434).

Thanks so much for looking at this.

2016-06-07 16:22 GMT+02:00 Steve Peak notifications@github.com:

**Pull request merged**
